# Generated by Django 5.1.7 on 2025-10-10 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('crop_detected', models.CharField(max_length=50)),
                ('disease_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
    ]
